// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'movieSearchActions': string;
  'movieSearchCell': string;
}
export const cssExports: CssExports;
export default cssExports;
