// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actionButton': string;
  'actionButtons': string;
  'enabled': string;
  'name': string;
  'nameContainer': string;
  'notification': string;
}
export const cssExports: CssExports;
export default cssExports;
